version: '3.8'

services:
    postgres:
        container_name: hakaton-postgres
        image: postgres:14.1-alpine3.15
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: db_name
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
